### PR TITLE
updated readme

### LINKED ISSUE #71: readme is outdated
readme points out `~/.antibody` and other stuff like that, which are not true anymore... 

Let's fix that!

### PR DESCRIPTION
**Pull request by caarlos0**
fixes #71 

@mkwmms, @oieduardorabelo, @nisaacson, @pragmaticivan, @wkentaro, @marceldias, @davidkna, can I cite your projects here?

### CODE REVIEW

**Comment by pragmaticivan** [comment]
Yes

**Comment by caarlos0** [comment]
@mkwmms, @oieduardorabelo, @nisaacson, @wkentaro, @marceldias, @davidkna: I'll merge this for now, please let me know if you want your names to be removed, ok?

Thanks

**Comment by marceldiass** [comment]
yes, you can :beers:

**Comment by mkwmms** [comment]
@caarlos0 for sure!

**Comment by wkentaro** [comment]
:+1:

**Comment by oieduardorabelo** [comment]
for sure, you remembered me , I need to update mine :package:

**Pull request merged**
