### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by mkwmms**

### CODE REVIEW

**Comment by caarlos0** [comment]
Many thanks!

**Comment by mkwmms** [comment]
No problem, this tool is awesome! I might also submit a PR sometime soon to allow for commenting out zsh packages in a bundle-file (which would then be ignored by antibody of course). Also maybe an unbundle option that would remove the requested package. I don't know Go at all though; although this would be a good excuse to learn!

**Comment by caarlos0** [comment]
@mkwmms Nice to hear that :dancer: 

Go is fairly easy to learn and fun to use too... BTW: you can open feature requests for these things if you want, the comment out feature seems pretty useful to me...

Cheers!

**Comment by mkwmms** [comment]
Ok thanks! I just figured for small stuff why not go ahead and do it :)

**Pull request merged**
